# Default values for bofh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 0

image:
  repository: ovalmoney/bofh
  tag: latest
  pullPolicy: Never

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9590

resources:
  limits:
    memory: 100Mi
    cpu: 100m
  requests:
    memory: 100Mi
    cpu: 100m

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: nodetype
              operator: In
              values:
              - myspecialnode
